name: tal-ml
channels:
  - conda-forge
  - defaults
dependencies:
  - beautifulsoup4=4.11
  - jupyterlab=3.4
  - matplotlib=3.5
  - nltk=3.6
  - numpy=1.23
  - pandas=1.4
  - pip
  - python=3.10
  - scikit-learn=1.1
  - scipy=1.9
  - scrapy=2.6
  - seaborn=0.11
  - pip:
    - git+https://github.com/ClaudeCoulombe/FrenchLefffLemmatizer.git
