name: TALA440C
channels:
  - conda-forge
  - defaults
dependencies:
  - gensim=4.3.2
  - jupyterlab=4.3.3
  - jupyterlab-latex=4.0
  - matplotlib=3.7
  - nltk=3.8
  - numpy
  - pandas=2.2.3
  - pillow=10.0
  - pip
  - python=3.11
  - scikit-learn
  - scipy
  - seaborn=0.13
  - tabulate=0.9.0
  - wordcloud=1.9.2
  - pip:
    - git+https://github.com/ClaudeCoulombe/FrenchLefffLemmatizer.git
