name: tal-ml
channels:
  - conda-forge
  - defaults
dependencies:
  - beautifulsoup4
  - jupyterlab=3.3
  - matplotlib
  - nltk==3.4.5
  - numpy
  - pandas
  - pip
  - rise
  - scikit-learn
  - scipy
  - scrapy
  - seaborn
  - pip:
    - git+https://github.com/ClaudeCoulombe/FrenchLefffLemmatizer.git
