name: tal-ml
channels:
  - conda-forge
  - defaults
dependencies:
  - beautifulsoup4=4.11
  - gensim=4.3.2
  - jupyterlab=3.4
  - jupyterlab-latex=3.1
  - matplotlib=3.5
  - nltk=3.6
  - numpy=1.23
  - pandas=1.4
  - pip
  - python=3.10
  - scikit-learn=1.3
  - scipy=1.9
  - scrapy=2.6
  - seaborn=0.11
  - tabulate=0.9.0
  - wordcloud=1.9.2
  - pip:
    - git+https://github.com/ClaudeCoulombe/FrenchLefffLemmatizer.git
