#!/bin/bash

#
# spacy
#
python -m spacy download fr_core_news_sm

#
# TreeTagger
#
# go to TT folder
cd ./7.pos-tagging/TreeTagger

# get Linux tagger package
wget https://cis.uni-muenchen.de/~schmid/tools/TreeTagger/data/tree-tagger-linux-3.2.5.tar.gz

# get tagging scripts
wget wget https://cis.uni-muenchen.de/~schmid/tools/TreeTagger/data/tagger-scripts.tar.gz

# get parameter files
wget https://cis.uni-muenchen.de/~schmid/tools/TreeTagger/data/english.par.gz
wget https://cis.uni-muenchen.de/~schmid/tools/TreeTagger/data/french.par.gz

# get installation script
wget https://cis.uni-muenchen.de/~schmid/tools/TreeTagger/data/install-tagger.sh

# install
sh install-tagger.sh